on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main


name: Build robot

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 20 ]
    name: Java ${{ matrix.java }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Package
        run: ./gradlew jar
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.java == '17'
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            build/libs/nfc4pc-*.jar
          fail_on_unmatched_files: true
          body: Release ${{ github.ref_name }}
          prerelease: true # manually promoted
